### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by schriftgestalt** [source-foundry/FilterListManager#11]
I got this from a user:
```
Details:
Traceback (most recent call last):

 File "~/Library/Application Support/Glyphs/Repositories/Filter List Manager (FLM)/FilterListManager.glyphsPlugin/Contents/Resources/plugin.py", line 88, in <module>
   shutil.copy(GLYPHS_PLIST_FILE, FLM_BACKUP_ORIGINAL_FILE)

 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 139, in copy
   copyfile(src, dst)

 File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
   with open(src, 'rb') as fsrc:

IOError: [Errno 2] No such file or directory: u'~/Library/Application Support/Glyphs/CustomFilter.plist'

App:2.6.5-1342 Plugin:0.5.1-51
```

**Comment by chrissimpkins** [comment]
Thank you for posting it here!  Is it possible to tell what version of the plugin they used?  It doesn't appear that we ever pushed a v0.5.1 as indicated in the trace there.  The latest v0.6.0 release includes the Py3 changes that you submitted to the repository and was released here in early June 2020.

**Comment by schriftgestalt** [comment]
It is in the last line of the report.

**Comment by chrissimpkins** [comment]
It looks like that is an old release.  Possible to ask the user to attempt an update to v0.6.0 and report directly in this thread? I can work with them on a fix.

**Comment by schriftgestalt** [comment]
The current version is 0.5.1-51. and the code at that location is not fixed

**Comment by chrissimpkins** [comment]
What is the current Py environment jn the release of the editor reported here?

**Comment by chrissimpkins** [comment]
> IOError: [Errno 2] No such file or directory: u'~/Library/Application Support/Glyphs/CustomFilter.plist'

Has the path to this Glyphs file been changed?

**Comment by chrissimpkins** [comment]
My understanding is that this is a default file distributed with releases, no?  Is this a situation where the user deleted it or should it not be there in some distributions?  In any case, it looks like we just need to catch the missing file path issue and raise a warning.

**Comment by schriftgestalt** [comment]
The file is created the first time the user changes the filters.

**Comment by chrissimpkins** [comment]
> The file is created the first time the user changes the filters.

ty!

**Comment by schriftgestalt** [comment]
Still not fixed??
